plugins {
    id 'java'
}

architectury {
    common rootProject.enabled_platforms.split(',')
}

java {
    withSourcesJar()
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

dependencies {
    // Fabric Loader is included here ONLY for access to @Environment annotations
    // Do NOT use other classes from the loader itself!
    modImplementation "net.fabricmc:fabric-loader:${rootProject.mc_1_21_1_fabric_loader_version}"
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
    it.options.encoding = 'UTF-8'
}

tasks.withType(Javadoc).configureEach {
    it.options.encoding = 'UTF-8'
}
