plugins {
    id 'com.gradleup.shadow'
}

architectury {
    platformSetupLoomIde()
    fabric()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common

    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${rootProject.mc_1_20_1_fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${rootProject.mc_1_20_1_fabric_api_version}"
    modImplementation "dev.architectury:architectury-fabric:${rootProject.mc_1_20_1_architectury_api_version}"

    common(project(path: ':1.20.1:common', configuration: 'namedElements')) { transitive false }
    shadowBundle project(path: ':1.20.1:common', configuration: 'transformProductionFabric')
}

processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') {
        expand version: project.version
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    inputFile.set shadowJar.archiveFile
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 17
    it.options.encoding = 'UTF-8'
}

tasks.withType(Javadoc).configureEach {
    it.options.encoding = 'UTF-8'
}
